In [54]:
import numpy as np

d = 10
m,n = 3, 4
A = np.random.rand(m,d)
B = np.random.rand(n,d)

C = np.zeros((m,n))
for i in range(d):
    C += A[:,[i]] @ B[:,[i]].T

In [55]:
C1 = np.zeros((m,n))
C2 = np.zeros((m,n))
for i in range(d):
    C1 += A[:,[i]] @ B[:,[i]].T
    C2 += np.outer(A[:, i], B[:, i])

In [56]:
C1 == C2

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
C1

array([[2.20925664, 3.92324837, 2.48450254, 1.8314681 ],
       [1.62492062, 2.63284094, 1.28044492, 1.27158114],
       [1.9722299 , 3.30252416, 1.73613303, 1.90864162]])

In [60]:
A @ B.T

array([[2.20925664, 3.92324837, 2.48450254, 1.8314681 ],
       [1.62492062, 2.63284094, 1.28044492, 1.27158114],
       [1.9722299 , 3.30252416, 1.73613303, 1.90864162]])