In [1]:
import numpy as np

d = 10
m,n = 3, 4
A = np.random.rand(m,d)
B = np.random.rand(n,d)

In [7]:
C1 = np.zeros((m,n))
C2 = np.zeros((m,n))
for i in range(m):
    for j in range(n):
        C1[i,j] = np.sum(A[i] * B[j])
        C2[i,j] = np.inner(A[i], B[j])

In [9]:
C1

array([[3.10304885, 3.1099058 , 2.18164883, 2.27283365],
       [2.26204255, 2.38469944, 1.61554036, 1.83020597],
       [3.27918674, 2.44967203, 2.07767483, 2.44043351]])

In [8]:
C2

array([[3.10304885, 3.1099058 , 2.18164883, 2.27283365],
       [2.26204255, 2.38469944, 1.61554036, 1.83020597],
       [3.27918674, 2.44967203, 2.07767483, 2.44043351]])

In [5]:
C = A @ B.T
C

array([[3.10304885, 3.1099058 , 2.18164883, 2.27283365],
       [2.26204255, 2.38469944, 1.61554036, 1.83020597],
       [3.27918674, 2.44967203, 2.07767483, 2.44043351]])

In [13]:
np.outer([2, 3], [3, 2])

array([[6, 4],
       [9, 6]])