In [42]:
import numpy as np
import timeit

m, n, d = 10, 10, 10
A = np.random.rand(m, d)
B = np.random.rand(n, d)

def f1(A, B):
    D = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            dot_product = np.dot(A[i], B[j])
            norm_A = np.linalg.norm(A[i])
            norm_B = np.linalg.norm(B[j])
            cosine_similarity = dot_product / (norm_A * norm_B)
            D[i, j] = 1 - cosine_similarity
    return D


def f2(A, B):
    C = 1 - (A @ B.T) / (np.sqrt(np.sum(A ** 2, axis=1, keepdims=True)) * np.sqrt(np.sum(B ** 2, axis=1)))
    return C

In [43]:
t1 = timeit.timeit(lambda :f1(A, B), number=1)
t2 = timeit.timeit(lambda :f2(A, B), number=1)

print(f'{t1:0.8f}')
print(f'{t2:0.8f}')
print(f'{(t1-t2)/t1 * 100:0.2f}% SpeedUp!!!')

0.00143710
0.00007910
94.50% SpeedUp!!!


In [51]:
CosDist_NonVec = np.round(f1(A, B), 5)
CosDist_Vec = np.round(f2(A, B), 5)

np.array_equal(CosDist_Vec, CosDist_NonVec)

True

In [57]:
f2(2*A, B)[0]

array([0.45745486, 0.30070617, 0.36815198, 0.29655488, 0.1514127 ,
       0.27599831, 0.24032961, 0.18545579, 0.23486242, 0.23072244])

In [62]:
f2(A, B)[0]

array([0.45745486, 0.30070617, 0.36815198, 0.29655488, 0.1514127 ,
       0.27599831, 0.24032961, 0.18545579, 0.23486242, 0.23072244])

In [64]:
f2(A**2, B)[0]

array([0.58748385, 0.36771883, 0.40415982, 0.40397982, 0.20378346,
       0.39993223, 0.32700866, 0.19832138, 0.26199471, 0.3087215 ])